### PR TITLE
Fixed multiple assignments of charging points

### LINKED ISSUE #56: Charging station receive duplicative arrivals
In `MobilitySimulator#handleParkingEvs`, EVs can be assigned to charging stations multiple times, possibly exceeding charging point limitations. This is because asssignments of EVs to charging stations are not tracked in `availableChargingPoints`.

https://github.com/ie3-institute/MobilitySimulator/blob/791a8f7591909ed0b9998c98b2dd79e6b14f88ef/src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala#L374-L379

### PR DESCRIPTION
**Pull request by sebastian-peter**
Resolves #56

Also changes the log output of evcs (`evcs.csv`) to include the uuids of parked EVs

### CODE REVIEW

**Review by staudtMarius — DISMISSED** [review]
Looks good.

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala [hunk 1]
```diff
@@ -176,8 +176,17 @@ final class MobilitySimulator(
...
+    // compile map from evcs to their parked evs
+    val evcsToParkedEvs = electricVehicles
+      .flatMap { ev =>
+        ev.getChosenChargingStation.map(ev -> _)
+      }
+      .groupMap { case (_, cs) =>
+        cs
+      } { case (ev, _) =>
+        ev
+      }
```
Comment (t-ober) [inline src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:189]: that is a cool function

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala [hunk 2]
```diff
@@ -192,7 +201,7 @@ final class MobilitySimulator(
     )
     val sortedSet = SortedSet
```
Comment (t-ober) [inline src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:202]: the sortedSet might be in need of a new name

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala [hunk 3]
```diff
@@ -154,7 +154,7 @@ final class MobilitySimulator(
       availableChargingPoints: Map[UUID, Int],
```
Comment (t-ober) [inline src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:154]: the `sendEvMovementsToSImona` has a pretty misleading name as we also get departures back. 
How about `exchangeEvMovementsWithSimona` ?

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala [hunk 4]
```diff
@@ -402,23 +405,23 @@ final class MobilitySimulator(
...
     chooseChargingStation(
       ev,
       pricesAtChargingStation,
       availableChargingPoints,
       MobilitySimulator.seed,
       maxDistance
     ).map { cs =>
-      val availableChargingPointsAtStation: Int =
+      val availableChargingPointsAtStation =
         availableChargingPoints.getOrElse(cs, 0)
```
Comment (t-ober) [inline src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:425]: So i learned about Design by contract recently and read advice about checking Preconditions of specific methods. In this case this would mean adding a `require(availableChargingPointsAtStation >= 0)` which seems pretty sensible in this case

**Review by t-ober — CHANGES_REQUESTED** [review]
Thanks just minor things 🙂

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala (hunk 3 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:154]: Good call

File: src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala (hunk 4 above)
Comment (sebastian-peter) [reply src/main/scala/edu/ie3/mobsim/MobilitySimulator.scala:425]: I definitely see the point if we'd call another method here that could check on `availableChargingPointsAtStation` again. Checking the variable right after the if condition that requires the same thing not so much, tbh.

**Review by t-ober — APPROVED** [review]
